### ISSUE TITLE
dvb-t/t2 outputs UK 

### ISSUE THREAD

**Issue by MikeB2013** [stefantalpalaru/w_scan2#8]
I am seeing some strange output for terrestrial in UK (GB) depending on setting of -f 

-ft (128 services)
Drama;(null):714000:B8:T:27500:6609=2:6610=eng@3,6611=eng:0;6614:0:16208:0:12294:0
BBC TWO HD;(null):474000:B8S1P0:T:27500:101=27:102=eng@17,106=eng:0;105:0:17472:0:16515:0
Sky News;(null):594000:B8:T:27500:101=2:102=eng@3,104=eng:0;103:0:22080:0:20544:0

-ft1 (98 services no HD dvb-t2)
Drama;(null):714000:B8:T:27500:6609=2:6610=eng@3,6611=eng:0;6614:0:16208:0:12294:0
Sky News;(null):594000:B8C34D0G32M64T8Y0:T:27500:101=2:102=eng@3,104=eng:0;103:0:22080:9018:20544:0

-ft2 (128 services)
Drama;(null):714000:B8C34D0G32M64T8Y0:T:27500:6609=2:6610=eng@3,6611=eng:0;6614:0:16208:9018:12294:0
BBC TWO HD;(null):474000:B8S1P0:T:27500:101=27:102=eng@17,106=eng:0;105:0:17472:0:16515:0
Sky News;(null):594000:B8C34D0G32M64T8Y0:T:27500:101=2:102=eng@3,104=eng:0;103:0:22080:9018:20544:0

default (128 services)
Drama;(null):714000:B8:T:27500:6609=2:6610=eng@3,6611=eng:0;6614:0:16208:0:12294:0
BBC TWO HD;(null):474000:B8S1P0:T:27500:101=27:102=eng@17,106=eng:0;105:0:17472:0:16515:0
Sky News;(null):594000:B8C34D0G32M64T8Y0:T:27500:101=2:102=eng@3,104=eng:0;103:0:22080:9018:20544:0

It seems that the vdr output is incomplete in some cases:
B8
B8S1P0

Attached are logs (zipped due to size)  for the outputs using -vvvvv

Also attached are the build logs for w_scan2 in case it helps.
built from source master bddf1e8 bump version 
Xubuntu 18.10 
kernel 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux  
I note the compiler is issuing some warnings about fallthrough and possible data overwrites.
[autogen.log.zip](https://github.com/stefantalpalaru/w_scan2/files/2522656/autogen.log.zip)
[config.log](https://github.com/stefantalpalaru/w_scan2/files/2522659/config.log)
[configure.log](https://github.com/stefantalpalaru/w_scan2/files/2522660/configure.log)
[make.log](https://github.com/stefantalpalaru/w_scan2/files/2522662/make.log)
[full_trace_wscan2_default.log.zip](https://github.com/stefantalpalaru/w_scan2/files/2522665/full_trace_wscan2_default.log.zip)
[full_trace_wscan2_ft.log.zip](https://github.com/stefantalpalaru/w_scan2/files/2522667/full_trace_wscan2_ft.log.zip)
[full_trace_wscan2_ft1.log.zip](https://github.com/stefantalpalaru/w_scan2/files/2522669/full_trace_wscan2_ft1.log.zip)
[full_trace_wscan2_ft2.log.zip](https://github.com/stefantalpalaru/w_scan2/files/2522670/full_trace_wscan2_ft2.log.zip)

Mike

**Comment by stefantalpalaru** [comment]
@DF5EQ, can you take a look?

**Comment by DF5EQ** [comment]
Interestingly "Drama" is found with -ft1 and -ft2, may be they send in both systems (DVB-T, DVB-T2).
But why with -ft1 B8 is output and with -ft2 B8C34D0G32M64T8Y0, I have no idea.
That -ft delivers B8 as -ft1 is explainable, because -ft scans first as -ft1 and then as -ft2 and if a service (transponder?) is found it is not overwritten (see -d).
How the output is generated I hadn't looked or worked at this.
Does VDR has problems with this outputs?
I always and only used VLC for checks.

**Comment by MikeB2013** [comment]
Another run using -d switch command i.e. w_scan2 -d -c GB -C GB -G -t3 -F -vvvvv -ft2

DVB-T2 services are not found, for services (dvb-t) that are found the format seems ok .e.g.
Drama;(null):714000:B8C34D0G32M64T8Y0:T:27500:6609=2:6610=eng@3,6611=eng:0;6614:0:16208:9018:12294:0:421

The DVB-T2 muxes are on 474000, 746000, 754000 all are  256QAM 32KE 2/3 40.2Mb/s  MPEG4


Attached is  the log file
[w_full_trace_scan2_with-d_switch_ft2_t3_F.txt.zip](https://github.com/stefantalpalaru/w_scan2/files/2522859/w_full_trace_scan2_with-d_switch_ft2_t3_F.txt.zip)

I am not using VDR, just the output format (-G) to allow creation of satip format data for use with minisatip server. This format is the only one that outputs the pmt_pid.

Mike

**Comment by DF5EQ** [comment]
Hi Mike,
not finding the DVB-T2 services seems to be the problem that Stefan had 
fixed with his fork from w_scan.
He said, that there were some overrides of services with later found 
transponders/services.
@Stefan: you may explain this better ...
Mike, can you roll back to commit 
e613bb6c74bf94ebd76916802106dd6b22ef0754 ,that's before I brought in the 
-ft1,-ft2.
So we can check if my changes introduced some unwanted behavior.
Sorry that I cannot check it, I'm not in your DVB environment, I'm in 
Austria/Innsbruck.

Am 28.10.2018 um 15:50 schrieb Mike Bibbings:

**Comment by stefantalpalaru** [comment]
> w_scan2 -d -c GB -C GB -G -t3 -F -vvvvv -ft2

"-d" will drop transponders with the same ID based on their scanning order. You probably don't want that.
"-C" is for setting the charset. Are you sure you want a "GB" charset instead of the default "UTF-8"?

The difference between "B8C34D0G32M64T8Y0" and "B8" in the VDR output comes from non-default values for coderate (C), coderate_LP (D), guard (G), modulation (M) and so on (see src/dump-vdr.c:479). Could it be that those values really are different in the DVB-T2 version of the channel?

**Comment by MikeB2013** [comment]
@DF5EQ 
Have rerun at commit e613bb6...
DVB-T2 muxes are found, with 128 services.
However the output format still has B8, B8S1P0 e.g. 
BBC TWO HD;(null):474000:B8S1P0:T:27500:101=27:102=eng@17,106=eng:0;105:0:17472:0:16515:0:100
Drama;(null):714000:B8:T:27500:6609=2:6610=eng@3,6611=eng:0;6614:0:16208:0:12294:0:421
Here is the log
[commit_e613bb6.txt.zip](https://github.com/stefantalpalaru/w_scan2/files/2522957/commit_e613bb6.txt.zip)

@stefantalpalaru
 
Character set UTF8 is probably better.

I don't understand details of  dvb-t2 muxes but they can contain both HD and SD channels within the same mux.

The Guard Interval is 1/128 for DVB-T2. Modulation 256qam, Transmission 32k

Mike

**Comment by DF5EQ** [comment]
Ok, than my changes didn't break the output. But that does not help you, to be honest I have no deep knowledge about digital TV, sorry.
DVB-T and DVB-T2 are only (for easiest understanding) modulation and protocol schemes.
They do not know what will be transported by them. SD and HD can be transmitted via both of them. Mostly DVB-T is SD and DVB-T2 is HD and SD.
How this is reflected in the observed parameters is out of my knowledge.
If you use other output formats you get more human readable text for all this B S P T ...
Does your application "minisatip server" have any problems with the output?
Do you know what it is complaining about?

**Comment by MikeB2013** [comment]
Tried other output formats, however I need an output that has pmt_pid, only -G option has this. The suppression in the output of some parameters is what is causing my confusion (the VDR spec http://www.vdr-wiki.de/wiki/index.php/Vdr(5) does not mention this). I suspect this suppression may be a side effect of how my DVB-T/T2 tuners respond. I have three different units (Astrometa, TBS 6280 and Hauppauge QuadHD) the linux drivers for each of these does auto switching between DVB-T/T2 internally.

minisatip server is an implementation of satip protocol (http://www.satip.info/resources) and looks like 
`
http://192.168.0.22:8080/?freq=474&bw=8&msys=dvbt2&mtype=64qam&gi=1128&fec=23&pids=0,18,101,102,106,105,100

`
I have resolved my issue by modifying an external bash script to handle the -G output that I get from w_scan2.

I will close this issue

Mike
